language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

before_install:
  - nvm install 7.5
  - java -version
  - javac -version
  - git clone https://github.com/treasure-data/digdag.git
  - cd digdag
  - ls
  - ./gradlew build
  - ./gradlew publish

install: true

before_script:
  - cd /home/travis/build/bwtakacy/digdag-slack
  - git clone https://github.com/bwtakacy/digdag-slack.git
  - ls
  - cd digdag
  - ls
  - cp digdag-plugin-utils/build/libs/digdag-plugin-utils-0.9.4-SNAPSHOT.jar ../digdag-slack/libs/
  - cp digdag-spi/build/libs/digdag-spi-0.9.4-SNAPSHOT.jar ../digdag-slack/libs/
  - cp digdag-client/build/libs/digdag-client-0.9.4-SNAPSHOT.jar ../digdag-slack/libs/
  - cd ../digdag-slack
  - gradle wrap

script: ./gradlew check
